INSERT INTO `pokemon` (`Id`, `Nombre`, `Imagen`, `Descripcion`, `NroPokedex`) VALUES 
(NULL, 'Bulbasaur', '/pokedex/assets/sprites/1.gif', 'Durante algún tiempo después de nacer, crece alimentándose de la semilla de su lomo.', '1'),
(NULL, 'Ivysaur', '/pokedex/assets/sprites/2.gif', 'Cuando le brotan los primeros brotes en la espalda, es señal de que crecerá flores grandes y vistosas.', '2'),
(NULL, 'Venusaur', '/pokedex/assets/sprites/3.gif', 'Los grandes pétalos de la flor en su lomo tienen la capacidad de lanzar polen venenoso.', '3'),
(NULL, 'Charmander', '/pokedex/assets/sprites/4.gif', 'Prefiere lugares calurosos. Cuando llueve, el vapor que genera al salirle fuego de la cola se torna más intenso.', '4'),
(NULL, 'Charmeleon', '/pokedex/assets/sprites/5.gif', 'Si irritan a Charmeleon, la llama que arde en la punta de su cola brilla más intensamente.', '5'),
(NULL, 'Charizard', '/pokedex/assets/sprites/6.gif', 'Escupe fuego lo suficientemente caliente como para derretir grandes rocas. Causa incendios forestales sin querer.', '6'),
(NULL, 'Squirtle', '/pokedex/assets/sprites/7.gif', 'Cuando se siente en peligro, se protege con el caparazón que lleva en la espalda y lanza agua a presión por la boca.', '7'),
(NULL, 'Wartortle', '/pokedex/assets/sprites/8.gif', 'Cada vez que nada, se le va endureciendo la capa de piel que recubre su caparazón.', '8'),
(NULL, 'Blastoise', '/pokedex/assets/sprites/9.gif', 'Carga agua a presión en su grueso caparazón y la dispara con gran precisión.', '9'),
(NULL, 'Caterpie', '/pokedex/assets/sprites/10.gif', 'Cuando se asusta, libera un hedor horrible por las antenas con el que repele a sus enemigos.', '10'),
(NULL, 'Metapod', '/pokedex/assets/sprites/11.gif', 'Su concha es dura, pero se mueve lentamente. Se cree que utiliza su concha para protegerse de los depredadores.', '11'),
(NULL, 'Butterfree', '/pokedex/assets/sprites/12.gif', 'En primavera, sale de su capullo y echa a volar. La polvareda de sus alas es irritante para los ojos.', '12'),
(NULL, 'Weedle', '/pokedex/assets/sprites/13.gif', 'Se trata de un pequeño Pokémon que se desplaza principalmente arrastrándose por el suelo.', '13'),
(NULL, 'Kakuna', '/pokedex/assets/sprites/14.gif', 'Una vez que Kakuna ha cerrado bien su caparazón duro, solo puede permanecer inmóvil.', '14'),
(NULL, 'Beedrill', '/pokedex/assets/sprites/15.gif', 'Vuela a gran velocidad y ataca con un aguijón venenoso que tiene en el extremo del brazo.', '15'),
(NULL, 'Pidgey', '/pokedex/assets/sprites/16.gif', 'Prefiere pelear con la fuerza del viento. Generalmente ataca a presas más grandes.', '16'),
(NULL, 'Pidgeotto', '/pokedex/assets/sprites/17.gif', 'Normalmente no se deja ver en vuelo. Ataca a presas más grandes que él.', '17'),
(NULL, 'Pidgeot', '/pokedex/assets/sprites/18.gif', 'Posee unas poderosas alas que le permiten volar a gran velocidad. Presume de su plumaje frente a los rivales.', '18'),
(NULL, 'Rattata', '/pokedex/assets/sprites/19.gif', 'Vive en cualquier sitio. Siempre que tenga comida cerca, no tendrá problemas de supervivencia.', '19'),
(NULL, 'Raticate', '/pokedex/assets/sprites/20.gif', 'Cuida con mucho celo su territorio. Si hay algo que no le guste, seguramente ataque.', '20'),
(NULL, 'Spearow', '/pokedex/assets/sprites/21.gif', 'Es muy agresivo y ataca en grupos organizados. Vive en cualquier parte.', '21'),
(NULL, 'Fearow', '/pokedex/assets/sprites/22.gif', 'Es muy grande y tiene un largo pico. Lo levanta muy alto para detectar presas.', '22'),
(NULL, 'Ekans', '/pokedex/assets/sprites/23.gif', 'Se mueve sin hacer ruido y se enrosca alrededor de su presa antes de apretarla hasta asfixiarla.', '23'),
(NULL, 'Arbok', '/pokedex/assets/sprites/24.gif', 'El patrón que tiene en la capucha cambia según su estado emocional. Puede tener varios patrones diferentes.', '24'),
(NULL, 'Pikachu', '/pokedex/assets/sprites/25.gif', 'Cuando se encuentra con algo nuevo, lo investiga metiéndoselo en la boca. Si es algo que le gusta, lo mordisqueará.', '25'),
(NULL, 'Raichu', '/pokedex/assets/sprites/26.gif', 'Si se carga de electricidad, su cola brilla y se pone más peligrosa.', '26'),
(NULL, 'Sandshrew', '/pokedex/assets/sprites/27.gif', 'Se enrolla para protegerse del frío. Cuando se siente amenazado, se esconde bajo la arena.', '27'),
(NULL, 'Sandslash', '/pokedex/assets/sprites/28.gif', 'Cava en el suelo para hacerse una madriguera. Vive en zonas rocosas y desérticas.', '28'),
(NULL, 'Nidoran♀', '/pokedex/assets/sprites/29.gif', 'Endurece la punta de su larga cola para hacerla aún más afilada. Da miedo acercarse a ella.', '29'),
(NULL, 'Nidorina', '/pokedex/assets/sprites/30.gif', 'Se dice que puede vivir en el agua, pero no hay pruebas de ello.', '30'),
(NULL, 'Nidoqueen', '/pokedex/assets/sprites/31.gif', 'A pesar de su aspecto fiero, es muy amable con los entrenadores de Pokémon, a los que trata como si fueran su propia cría.', '31'),
(NULL, 'Nidoran♂', '/pokedex/assets/sprites/32.gif', 'A pesar de ser venenoso, se dice que no ataca a menos que se sienta en peligro.', '32'),
(NULL, 'Nidorino', '/pokedex/assets/sprites/33.gif', 'Tiene una naturaleza violenta y muy competitiva. Sus dientes y cuernos son extremadamente afilados.', '33'),
(NULL, 'Nidoking', '/pokedex/assets/sprites/34.gif', 'Su cuerpo es más duro que el diamante. Sus dientes y cuernos son capaces de perforar rocas y acero.', '34'),
(NULL, 'Clefairy', '/pokedex/assets/sprites/35.gif', 'Su cuerpo está compuesto en su mayoría por agua. Si se queda sin hidratarse, se marchita.', '35'),
(NULL, 'Clefable', '/pokedex/assets/sprites/36.gif', 'Es muy popular entre las mujeres. Suele ser la estrella en representaciones de la luna llena.', '36'),
(NULL, 'Vulpix', '/pokedex/assets/sprites/37.gif', 'Cuando se ve en peligro, escupe llamas por la boca y se envuelve en una bola de fuego para huir.', '37'),
(NULL, 'Ninetales', '/pokedex/assets/sprites/38.gif', 'Es muy inteligente y sabe exactamente lo que hace. Es capaz de controlar las llamas que maneja.', '38'),
(NULL, 'Jigglypuff', '/pokedex/assets/sprites/39.gif', 'Canta una nana que pone a dormir a su rival. Se le infla el cuerpo cuando lo hace.', '39'),
(NULL, 'Wigglytuff', '/pokedex/assets/sprites/40.gif', 'Posee una delicadeza extraordinaria. Puede inflar su cuerpo hasta el doble de tamaño.', '40'),
(NULL, 'Zubat', '/pokedex/assets/sprites/41.gif', 'Evita la luz solar. Se esconde en cuevas durante el día y vuela por la noche para buscar presas.', '41'),
(NULL, 'Golbat', '/pokedex/assets/sprites/42.gif', 'Además de alimentarse de fruta, le gusta beber sangre humana. Dicen que ha habido casos de personas atacadas por él en la oscuridad.', '42'),
(NULL, 'Oddish', '/pokedex/assets/sprites/43.gif', 'Se mueve como si estuviera danzando. A veces se le puede ver en los campos a la luz de la luna.', '43'),
(NULL, 'Gloom', '/pokedex/assets/sprites/44.gif', 'Lanza un olor tan intenso que nadie puede acercarse a menos de 1 km. Sin embargo, hay quien lo considera un buen olor.', '44'),
(NULL, 'Vileplume', '/pokedex/assets/sprites/45.gif', 'Cuando florece, dispersa un polen nocivo y altamente alucinógeno que causa estornudos y llanto.', '45'),
(NULL, 'Paras', '/pokedex/assets/sprites/46.gif', 'Crece alimentándose de la savia de los árboles. Se desplaza muy lentamente.', '46'),
(NULL, 'Parasect', '/pokedex/assets/sprites/47.gif', 'El parásito se apodera del cuerpo y el alma de Parasect. La seta crece sobre él y lo controla.', '47'),
(NULL, 'Venonat', '/pokedex/assets/sprites/48.gif', 'Sus grandes ojos son extremadamente sensibles a la luz. Por eso, vive en cuevas oscuras y húmedas.', '48'),
(NULL, 'Venomoth', '/pokedex/assets/sprites/49.gif', 'Su cuerpo está cubierto de escamas en las que se encuentran toxinas que provocan parálisis.', '49'),
(NULL, 'Diglett', '/pokedex/assets/sprites/50.gif', 'Vive en el subsuelo y es capaz de excavar un túnel de 100 metros en una noche de luna llena.', '50'),
(NULL, 'Dugtrio', '/pokedex/assets/sprites/51.gif', 'Excava un túnel de 100 kilómetros de longitud en una sola noche de luna llena.', '51'),
(NULL, 'Meowth', '/pokedex/assets/sprites/52.gif', 'Tiene un carácter extremadamente feroz. Sin embargo, una vez que se familiariza con alguien, se comporta cariñosamente.', '52'),
(NULL, 'Persian', '/pokedex/assets/sprites/53.gif', 'Sus largas y delgadas extremidades le permiten caminar sin hacer ruido. Es un depredador nocturno.', '53'),
(NULL, 'Psyduck', '/pokedex/assets/sprites/54.gif', 'Más que usar la capacidad cerebral que tiene en la cabeza, parece que utiliza su corazón para luchar.', '54'),
(NULL, 'Golduck', '/pokedex/assets/sprites/55.gif', 'Es un nadador muy competente. Se ha dicho que podría cruzar el Canal de la Mancha nadando.', '55'),
(NULL, 'Mankey', '/pokedex/assets/sprites/56.gif', 'Vive en bosques densos. Cuando se enfada, se desata y no se calma hasta que no ha destrozado todo.', '56'),
(NULL, 'Primeape', '/pokedex/assets/sprites/57.gif', 'Con la fuerza de sus brazos, es capaz de doblar una viga de acero. Es muy difícil de controlar.', '57'),
(NULL, 'Growlithe', '/pokedex/assets/sprites/58.gif', 'Es muy leal a su entrenador y lo defiende de cualquier ataque, por peligroso que sea.', '58'),
(NULL, 'Arcanine', '/pokedex/assets/sprites/59.gif', 'Es capaz de correr a 100 km/h. Su melena arde en el mismo tono que el fuego que echa por la boca.', '59'),
(NULL, 'Poliwag', '/pokedex/assets/sprites/60.gif', 'Se dice que el vórtice que lleva en el abdomen se originó en las inagotables fuentes de agua.', '60'),
(NULL, 'Poliwhirl', '/pokedex/assets/sprites/61.gif', 'La espiral que lleva en el abdomen contiene un líquido. Dicen que puede regenerar extremidades amputadas.', '61'),
(NULL, 'Poliwrath', '/pokedex/assets/sprites/62.gif', 'Su cuerpo es resistente a los golpes. Los puñetazos de Poliwrath pueden partir un bloque de cemento con facilidad.', '62'),
(NULL, 'Abra', '/pokedex/assets/sprites/63.gif', 'Es muy tímido y suele esconderse en la hierba. Se le escapa si te descuidas.', '63'),
(NULL, 'Kadabra', '/pokedex/assets/sprites/64.gif', 'Ha demostrado tener una capacidad intelectual muy alta. Puede prever el futuro por la posición de las estrellas.', '64'),
(NULL, 'Alakazam', '/pokedex/assets/sprites/65.gif', 'Sus células cerebrales se han multiplicado tanto que ha desarrollado más poderes. Es un Pokémon muy inteligente.', '65'),
(NULL, 'Machop', '/pokedex/assets/sprites/66.gif', 'Más que usar la capacidad cerebral que tiene en la cabeza, parece que utiliza su corazón para luchar.', '66'),
(NULL, 'Machoke', '/pokedex/assets/sprites/67.gif', 'Es muy fuerte y es capaz de lanzar un golpe tan potente que es capaz de derribar a un elefante.', '67'),
(NULL, 'Machamp', '/pokedex/assets/sprites/68.gif', 'Su fuerza es ilimitada. Puede lanzar cien golpes por segundo y alcanzar una velocidad de mach 2.', '68'),
(NULL, 'Bellsprout', '/pokedex/assets/sprites/69.gif', 'Cuando detecta la presa, se balancea y lanza el tentáculo como un látigo para atraparla.', '69'),
(NULL, 'Weepinbell', '/pokedex/assets/sprites/70.gif', 'Atrae a sus presas con una dulce fragancia que desprende de la babosa que tiene en la cabeza.', '70'),
(NULL, 'Victreebel', '/pokedex/assets/sprites/71.gif', 'Devora a su presa sin piedad. Sus enormes fauces le permiten tragar cosas grandes de un solo bocado.', '71'),
(NULL, 'Tentacool', '/pokedex/assets/sprites/72.gif', 'En aguas cálidas, nadan en grupos. Se dice que las mareas aumentan cuando aparecen.', '72'),
(NULL, 'Tentacruel', '/pokedex/assets/sprites/73.gif', 'Su cuerpo está formado por más del 90% de agua. A veces, arrasa pueblos enteros en la costa.', '73'),
(NULL, 'Geodude', '/pokedex/assets/sprites/74.gif', 'Cuando se le acaba la energía, se convierte en una roca y se queda dormido. Hasta el ruido de una demolición lo despierta.', '74'),
(NULL, 'Graveler', '/pokedex/assets/sprites/75.gif', 'Le gusta rodar colina abajo para desplazarse. A veces, se cae por los acantilados sin querer.', '75'),
(NULL, 'Golem', '/pokedex/assets/sprites/76.gif', 'Pesa más de 600 kg. Si empieza a rodar colina abajo, nada puede pararlo.', '76'),
(NULL, 'Ponyta', '/pokedex/assets/sprites/77.gif', 'Galopa a toda velocidad. Siempre que hay corrientes de aire, se le puede ver corriendo por las llanuras a toda velocidad.', '77'),
(NULL, 'Rapidash', '/pokedex/assets/sprites/78.gif', 'Posee una velocidad de vértigo. Siempre que corre, se envuelve en llamas.', '78'),
(NULL, 'Slowpoke', '/pokedex/assets/sprites/79.gif', 'Su cuerpo está relleno de órganos muy lentos. Parece que hay algo que lo hace funcionar más lento de lo normal.', '79'),
(NULL, 'Slowbro', '/pokedex/assets/sprites/80.gif', 'Si alguien le arranca la concha, se le despierta un poder oculto y se vuelve mucho más violento.', '80'),
(NULL, 'Magnemite', '/pokedex/assets/sprites/81.gif', 'Está compuesto de magnetita. Algunas veces, se junta con otros Magnemite y forman un Magneton.', '81'),
(NULL, 'Magneton', '/pokedex/assets/sprites/82.gif', 'Si uno de los imanes falla, se separa del grupo y se convierte en un Magnemite independiente.', '82'),
(NULL, 'Farfetch’d', '/pokedex/assets/sprites/83.gif', 'Este Pokémon salvaje lleva un puerro en la ala todo el tiempo. Se lo come junto con las setas que encuentra.', '83'),
(NULL, 'Doduo', '/pokedex/assets/sprites/84.gif', 'Corre muy rápido y no necesita alas para volar. Despliega sus dos cabezas para darle más velocidad.', '84'),
(NULL, 'Dodrio', '/pokedex/assets/sprites/85.gif', 'No puede volar, pero salta muy alto. En una lucha, puede clavar las tres cabezas en su rival a la vez.', '85'),
(NULL, 'Seel', '/pokedex/assets/sprites/86.gif', 'Se le encuentra con frecuencia en zonas con temperaturas bajo cero. En la orilla de los lagos se ve a menudo a Seel jugando en la nieve.', '86'),
(NULL, 'Dewgong', '/pokedex/assets/sprites/87.gif', 'Es muy juguetón y suele hacer volteretas y piruetas. A veces las hace en la orilla del mar, saltando sobre las olas.', '87'),
(NULL, 'Grimer', '/pokedex/assets/sprites/88.gif', 'Es un líquido viscoso con olor a desecho. Todo lo que toca se le pega.', '88'),
(NULL, 'Muk', '/pokedex/assets/sprites/89.gif', 'Es muy elástico y puede estirarse para capturar a su presa. A veces se cae y se queda pegajoso.', '89'),
(NULL, 'Shellder', '/pokedex/assets/sprites/90.gif', 'Se adhiere firmemente a las rocas y no se mueve de ahí. Se alimenta de algas que flotan en el agua.', '90'),
(NULL, 'Cloyster', '/pokedex/assets/sprites/91.gif', 'El órgano interno que tiene en la concha es muy duro. Puede soportar incluso los ataques más fuertes.', '91'),
(NULL, 'Gastly', '/pokedex/assets/sprites/92.gif', 'Es capaz de ocultarse en la oscuridad. Puede meterse en cualquier sitio sin que nadie lo note.', '92'),
(NULL, 'Haunter', '/pokedex/assets/sprites/93.gif', 'Si sientes un frío repentino, es una señal de que un Haunter está cerca. Dicen que los fantasmas lo producen.', '93'),
(NULL, 'Gengar', '/pokedex/assets/sprites/94.gif', 'Lanza maldiciones de terror. Puede entrar en la sombra de cualquiera y aparecer de la oscuridad.', '94'),
(NULL, 'Onix', '/pokedex/assets/sprites/95.gif', 'Excava túneles subterráneos de 10 km de profundidad para encontrar minerales.', '95'),
(NULL, 'Drowzee', '/pokedex/assets/sprites/96.gif', 'Duerme el 18 horas al día. Le encanta comer los sueños de la gente.', '96'),
(NULL, 'Hypno', '/pokedex/assets/sprites/97.gif', 'Atrae a la gente con su extraño hipnotismo y les roba los sueños que tienen en la fase REM.', '97'),
(NULL, 'Krabby', '/pokedex/assets/sprites/98.gif', 'Es de mar abierto, pero suele subir a ríos y arroyos. Se le puede ver cazando en la orilla.', '98'),
(NULL, 'Kingler', '/pokedex/assets/sprites/99.gif', 'Es un buen nadador. También puede vivir en tierra, pero se mantiene alejado de la arena.', '99'),
(NULL, 'Voltorb', '/pokedex/assets/sprites/100.gif', 'Es extremadamente sensible a las fuerzas magnéticas. Se dice que pueden ser causadas por su propio magnetismo.', '100'),
(NULL, 'Electrode', '/pokedex/assets/sprites/101.gif', 'Es muy peligroso. Tiene un gran poder explosivo. Quienes lo ven caminar sobre su propia energía huyen aterrorizados.', '101'),
(NULL, 'Exeggcute', '/pokedex/assets/sprites/102.gif', 'Suelen juntarse seis y dormir en grupo. El grupo completo se despierta si alguno de los seis se asusta.', '102'),
(NULL, 'Exeggutor', '/pokedex/assets/sprites/103.gif', 'Los Exeggutor más altos tienen cabeza en su cola. La cabeza tarda cinco segundos en darse cuenta de que está siendo atacada.', '103'),
(NULL, 'Cubone', '/pokedex/assets/sprites/104.gif', 'Carga un hueso que encontró de su madre muerta. Hay quienes afirman haber visto la figura de la madre en la luna mientras llora.', '104'),
(NULL, 'Marowak', '/pokedex/assets/sprites/105.gif', 'Su espada es una maravilla de la naturaleza. Dicen que puede atravesar una piedra con una simple sacudida de su cola.', '105'),
(NULL, 'Hitmonlee', '/pokedex/assets/sprites/106.gif', 'Extiende sus piernas para hacer una gama amplia de golpes que ningún otro Pokémon puede igualar.', '106'),
(NULL, 'Hitmonchan', '/pokedex/assets/sprites/107.gif', 'Le gusta cerrar el ring con su punzón en la mano. A veces gana sin tener que pelear.', '107'),
(NULL, 'Lickitung', '/pokedex/assets/sprites/108.gif', 'Se mueve lentamente, pero su lengua es increíblemente rápida. Puede lamer a 100 personas en menos de una hora.', '108'),
(NULL, 'Koffing', '/pokedex/assets/sprites/109.gif', 'Se desplaza a la deriva por el aire. Si encuentra una presa, expulsa gas venenoso de su cuerpo.', '109'),
(NULL, 'Weezing', '/pokedex/assets/sprites/110.gif', 'Le gusta más el aire limpio. Se alimenta de gases venenosos que encuentra por ahí.', '110'),
(NULL, 'Rhyhorn', '/pokedex/assets/sprites/111.gif', 'En una lucha, puede partir un árbol de un solo cabezazo. Una embestida suya puede destruir un edificio.', '111'),
(NULL, 'Rhydon', '/pokedex/assets/sprites/112.gif', 'Es increíblemente fuerte. Su cuerno tiene la dureza de diamante y puede perforar fácilmente cualquier cosa.', '112'),
(NULL, 'Chansey', '/pokedex/assets/sprites/113.gif', 'Se le considera de buen agüero. Se dice que quien ve a uno podrá vivir una vida feliz y plena.', '113'),
(NULL, 'Tangela', '/pokedex/assets/sprites/114.gif', 'Cuando está muy excitado, su cuerpo se extiende, lo que le permite a Tangela atrapar a sus presas con facilidad.', '114'),
(NULL, 'Kangaskhan', '/pokedex/assets/sprites/115.gif', 'Se dice que la madre se pelea por su cría. Vive en el bosque.', '115'),
(NULL, 'Horsea', '/pokedex/assets/sprites/116.gif', 'Puede nadar en el mar o en los ríos. A veces, nada en grupos de 100 o más.', '116'),
(NULL, 'Seadra', '/pokedex/assets/sprites/117.gif', 'Caza usando el rabo como si fuera un látigo para atrapar a su presa. La engulle cuando está medio muerta.', '117'),
(NULL, 'Goldeen', '/pokedex/assets/sprites/118.gif', 'Cuando nada río arriba para desovar, es fácil verlo saltando por las cataratas.', '118'),
(NULL, 'Seaking', '/pokedex/assets/sprites/119.gif', 'Es muy agresivo y ataca con cuerno y cola. Durante la época de cría, su rojo cuerno crece enormemente.', '119'),
(NULL, 'Staryu', '/pokedex/assets/sprites/120.gif', 'Los cristales que lleva en su cuerpo son muy valorados como gema. Dicen que se parecen a una estrella.', '120'),
(NULL, 'Starmie', '/pokedex/assets/sprites/121.gif', 'Su cuerpo es de cristal. Se dice que se originó en un meteorito que cayó en las montañas hace tiempo.', '121'),
(NULL, 'Mr. Mime', '/pokedex/assets/sprites/122.gif', 'Es muy hábil en la imitación. Es capaz de hacer parecer que la realidad es una ilusión y viceversa.', '122'),
(NULL, 'Scyther', '/pokedex/assets/sprites/123.gif', 'Sus afiladas garras son poderosas armas. Pueden partir un árbol de un solo golpe.', '123'),
(NULL, 'Jynx', '/pokedex/assets/sprites/124.gif', 'Baila de forma sexy para confundir a sus rivales y lanza un potente beso que congela al instante.', '124'),
(NULL, 'Electabuzz', '/pokedex/assets/sprites/125.gif', 'Se encuentra con frecuencia en tormentas eléctricas. Le gusta mucho la electricidad.', '125'),
(NULL, 'Magmar', '/pokedex/assets/sprites/126.gif', 'Las llamas ardientes que escupe por la boca son de 2.200 grados. Siempre está respirando fuego.', '126'),
(NULL, 'Pinsir', '/pokedex/assets/sprites/127.gif', 'Es muy fuerte y se le teme. Con sus potentes mandíbulas, puede cortar un árbol de un solo mordisco.', '127'),
(NULL, 'Tauros', '/pokedex/assets/sprites/128.gif', 'Este Pokémon se enfurece con la más mínima provocación y no se calma hasta que no ha destruido todo a su paso.', '128'),
(NULL, 'Magikarp', '/pokedex/assets/sprites/129.gif', 'Puede sobrevivir en cualquier medio acuático. Incluso puede vivir en aguas contaminadas.', '129'),
(NULL, 'Gyarados', '/pokedex/assets/sprites/130.gif', 'Dicen que cuando enfurece, causa tormentas. En algunas regiones, se le conoce como el destructor.', '130'),
(NULL, 'Lapras', '/pokedex/assets/sprites/131.gif', 'Es muy inteligente y es capaz de entender el lenguaje humano. Tiene un alto sentido de la justicia.', '131'),
(NULL, 'Ditto', '/pokedex/assets/sprites/132.gif', 'Puede cambiar de forma para parecerse a cualquier Pokémon o persona. Dicen que siempre es una copia exacta.', '132'),
(NULL, 'Eevee', '/pokedex/assets/sprites/133.gif', 'Puede evolucionar en varios tipos diferentes dependiendo de la piedra que lleve.', '133'),
(NULL, 'Vaporeon', '/pokedex/assets/sprites/134.gif', 'Su piel se convierte en una fina capa que le permite nadar a gran velocidad.', '134'),
(NULL, 'Jolteon', '/pokedex/assets/sprites/135.gif', 'Sus finos pelos generan electricidad estática. Pueden provocar descargas eléctricas al tocarlo.', '135'),
(NULL, 'Flareon', '/pokedex/assets/sprites/136.gif', 'La temperatura de su cuerpo aumenta cuando se siente emocionado. En ese momento, libera una cantidad de calor impresionante.', '136'),
(NULL, 'Porygon', '/pokedex/assets/sprites/137.gif', 'Se formó por la programación de una computadora. Es capaz de moverse y pensar de forma independiente.', '137'),
(NULL, 'Omanyte', '/pokedex/assets/sprites/138.gif', 'Vivía en los mares hace 100 millones de años. Se encuentra con frecuencia entre fósiles de conchas.', '138'),
(NULL, 'Omastar', '/pokedex/assets/sprites/139.gif', 'Una vez que tiene enemigos a la vista, dispara tentáculos pegajosos para atraparlos y luego los devora.', '139'),
(NULL, 'Kabuto', '/pokedex/assets/sprites/140.gif', 'Vivió hace 300 millones de años. Se considera un fósil, pero sigue siendo capaz de vivir en el agua.', '140'),
(NULL, 'Kabutops', '/pokedex/assets/sprites/141.gif', 'Cuando entra en contacto con agua, Kabutops puede respirar y moverse con facilidad.', '141'),
(NULL, 'Aerodactyl', '/pokedex/assets/sprites/142.gif', 'Este Pokémon es un antiguo habitante de los cielos. Se cree que era capaz de volar.', '142'),
(NULL, 'Snorlax', '/pokedex/assets/sprites/143.gif', 'Siempre está durmiendo y comiendo. Nunca deja de buscar comida ni de dormir.', '143'),
(NULL, 'Articuno', '/pokedex/assets/sprites/144.gif', 'Es un legendario pájaro Pokémon que puede congelar el aire húmedo en su entorno para crear una tormenta de nieve.', '144'),
(NULL, 'Zapdos', '/pokedex/assets/sprites/145.gif', 'Es un legendario pájaro Pokémon que crea rayos al agitar sus alas. Se dice que causa tormentas eléctricas.', '145'),
(NULL, 'Moltres', '/pokedex/assets/sprites/146.gif', 'Es un legendario pájaro Pokémon que puede controlar el fuego. Vuela por el cielo arrojando llamas.', '146'),
(NULL, 'Dratini', '/pokedex/assets/sprites/147.gif', 'Sus largas aletas le permiten nadar a una velocidad de 8 nudos. Es un excelente nadador.', '147'),
(NULL, 'Dragonair', '/pokedex/assets/sprites/148.gif', 'Es capaz de volar a una altitud de 6.600 pies. A veces se le ve volando a lo largo de las laderas de las montañas.', '148'),
(NULL, 'Dragonite', '/pokedex/assets/sprites/149.gif', 'Es una criatura muy amable. Aunque su fuerza y ​​ferocidad lo convierten en un poderoso oponente en la batalla.', '149'),
(NULL, 'Mewtwo', '/pokedex/assets/sprites/150.gif', 'Un Pokémon artificial creado mediante ingeniería genética. Se dice que fue creado a partir del ADN de Mew.', '150'),
(NULL, 'Mew', '/pokedex/assets/sprites/151.gif', 'Es capaz de aprender y usar cualquier movimiento de Pokémon. Su ADN es muy parecido al de Mewtwo.', '151');
