START TRANSACTION;
-- Base de datos: `pokedexpw2`
-- Estructura de tabla para la tabla `pokemon`
CREATE TABLE `pokemon` (
  `Id` int(11) NOT NULL,
  `Nombre` varchar(20) NOT NULL,
  `Imagen` text NOT NULL,
  `Descripcion` text NOT NULL,
  `NroPokedex` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Volcado de datos para la tabla `pokemon`
INSERT INTO `pokemon` (`Id`, `Nombre`, `Imagen`, `Descripcion`, `NroPokedex`) VALUES
(2, 'Ivysaur', '/pokedex/assets/sprites/2.gif', 'Cuando le brotan los primeros brotes en la espalda, es señal de que crecerá flores grandes y vistosas.', 2),
(3, 'Venusaur', '/pokedex/assets/sprites/3.gif', 'Los grandes pétalos de la flor en su lomo tienen la capacidad de lanzar polen venenoso.', 3),
(4, 'Charmander', '/pokedex/assets/sprites/4.gif', 'Prefiere lugares calurosos. Cuando llueve, el vapor que genera al salirle fuego de la cola se torna más intenso.', 4),
(5, 'Charmeleon', '/pokedex/assets/sprites/5.gif', 'Si irritan a Charmeleon, la llama que arde en la punta de su cola brilla más intensamente.', 5),
(6, 'Charizard', '/pokedex/assets/sprites/6.gif', 'Escupe fuego lo suficientemente caliente como para derretir grandes rocas. Causa incendios forestales sin querer.', 6),
(7, 'Squirtle', '/pokedex/assets/sprites/7.gif', 'Cuando se siente en peligro, se protege con el caparazón que lleva en la espalda y lanza agua a presión por la boca.', 7),
(8, 'Wartortle', '/pokedex/assets/sprites/8.gif', 'Cada vez que nada, se le va endureciendo la capa de piel que recubre su caparazón.', 8),
(9, 'Blastoise', '/pokedex/assets/sprites/9.gif', 'Carga agua a presión en su grueso caparazón y la dispara con gran precisión.', 9),
(10, 'Caterpie', '/pokedex/assets/sprites/10.gif', 'Cuando se asusta, libera un hedor horrible por las antenas con el que repele a sus enemigos.', 10),
(11, 'Metapod', '/pokedex/assets/sprites/11.gif', 'Su concha es dura, pero se mueve lentamente. Se cree que utiliza su concha para protegerse de los depredadores. Un kapo total', 11),
(12, 'Butterfree', '/pokedex/assets/sprites/12.gif', 'En primavera, sale de su capullo y echa a volar. La polvareda de sus alas es irritante para los ojos.', 12),
(13, 'Weedle', '/pokedex/assets/sprites/13.gif', 'Se trata de un pequeño Pokémon que se desplaza principalmente arrastrándose por el suelo.', 13),
(14, 'Kakuna', '/pokedex/assets/sprites/14.gif', 'Una vez que Kakuna ha cerrado bien su caparazón duro, solo puede permanecer inmóvil.', 14),
(15, 'Beedrill', '/pokedex/assets/sprites/15.gif', 'Vuela a gran velocidad y ataca con un aguijón venenoso que tiene en el extremo del brazo.', 15),
(16, 'Pidgey', '/pokedex/assets/sprites/16.gif', 'Prefiere pelear con la fuerza del viento. Generalmente ataca a presas más grandes.', 16),
(17, 'Pidgeotto', '/pokedex/assets/sprites/17.gif', 'Normalmente no se deja ver en vuelo. Ataca a presas más grandes que él.', 17),
(18, 'Pidgeot', '/pokedex/assets/sprites/18.gif', 'Posee unas poderosas alas que le permiten volar a gran velocidad. Presume de su plumaje frente a los rivales.', 18),
(19, 'Rattata', '/pokedex/assets/sprites/19.gif', 'Vive en cualquier sitio. Siempre que tenga comida cerca, no tendrá problemas de supervivencia.', 19),
(20, 'Raticate', '/pokedex/assets/sprites/20.gif', 'Cuida con mucho celo su territorio. Si hay algo que no le guste, seguramente ataque.', 20),
(21, 'Spearow', '/pokedex/assets/sprites/21.gif', 'Es muy agresivo y ataca en grupos organizados. Vive en cualquier parte.', 21),
(22, 'Fearow', '/pokedex/assets/sprites/22.gif', 'Es muy grande y tiene un largo pico. Lo levanta muy alto para detectar presas.', 22),
(23, 'Ekans', '/pokedex/assets/sprites/23.gif', 'Se mueve sin hacer ruido y se enrosca alrededor de su presa antes de apretarla hasta asfixiarla.', 23),
(24, 'Arbok', '/pokedex/assets/sprites/24.gif', 'El patrón que tiene en la capucha cambia según su estado emocional. Puede tener varios patrones diferentes.', 24),
(25, 'Pikachu', '/pokedex/assets/sprites/25.gif', 'Cuando se encuentra con algo nuevo, lo investiga metiéndoselo en la boca. Si es algo que le gusta, lo mordisqueará.', 25),
(26, 'Raichu', '/pokedex/assets/sprites/26.gif', 'Si se carga de electricidad, su cola brilla y se pone más peligrosa.', 26),
(27, 'Sandshrew', '/pokedex/assets/sprites/27.gif', 'Se enrolla para protegerse del frío. Cuando se siente amenazado, se esconde bajo la arena.', 27),
(28, 'Sandslash', '/pokedex/assets/sprites/28.gif', 'Cava en el suelo para hacerse una madriguera. Vive en zonas rocosas y desérticas.', 28),
(29, 'Nidoran♀', '/pokedex/assets/sprites/29.gif', 'Endurece la punta de su larga cola para hacerla aún más afilada. Da miedo acercarse a ella.', 29),
(30, 'Nidorina', '/pokedex/assets/sprites/30.gif', 'Se dice que puede vivir en el agua, pero no hay pruebas de ello.', 30),
(31, 'Nidoqueen', '/pokedex/assets/sprites/31.gif', 'A pesar de su aspecto fiero, es muy amable con los entrenadores de Pokémon, a los que trata como si fueran su propia cría.', 31),
(32, 'Nidoran♂', '/pokedex/assets/sprites/32.gif', 'A pesar de ser venenoso, se dice que no ataca a menos que se sienta en peligro.', 32),
(33, 'Nidorino', '/pokedex/assets/sprites/33.gif', 'Tiene una naturaleza violenta y muy competitiva. Sus dientes y cuernos son extremadamente afilados.', 33),
(34, 'Nidoking', '/pokedex/assets/sprites/34.gif', 'Su cuerpo es más duro que el diamante. Sus dientes y cuernos son capaces de perforar rocas y acero.', 34),
(35, 'Clefairy', '/pokedex/assets/sprites/35.gif', 'Su cuerpo está compuesto en su mayoría por agua. Si se queda sin hidratarse, se marchita.', 35),
(36, 'Clefable', '/pokedex/assets/sprites/36.gif', 'Es muy popular entre las mujeres. Suele ser la estrella en representaciones de la luna llena.', 36),
(37, 'Vulpix', '/pokedex/assets/sprites/37.gif', 'Cuando se ve en peligro, escupe llamas por la boca y se envuelve en una bola de fuego para huir.', 37),
(38, 'Ninetales', '/pokedex/assets/sprites/38.gif', 'Es muy inteligente y sabe exactamente lo que hace. Es capaz de controlar las llamas que maneja.', 38),
(39, 'Jigglypuff', '/pokedex/assets/sprites/39.gif', 'Canta una nana que pone a dormir a su rival. Se le infla el cuerpo cuando lo hace.', 39),
(40, 'Wigglytuff', '/pokedex/assets/sprites/40.gif', 'Posee una delicadeza extraordinaria. Puede inflar su cuerpo hasta el doble de tamaño.', 40),
(41, 'Zubat', '/pokedex/assets/sprites/41.gif', 'Evita la luz solar. Se esconde en cuevas durante el día y vuela por la noche para buscar presas.', 41),
(42, 'Golbat', '/pokedex/assets/sprites/42.gif', 'Además de alimentarse de fruta, le gusta beber sangre humana. Dicen que ha habido casos de personas atacadas por él en la oscuridad.', 42),
(43, 'Oddish', '/pokedex/assets/sprites/43.gif', 'Se mueve como si estuviera danzando. A veces se le puede ver en los campos a la luz de la luna.', 43),
(44, 'Gloom', '/pokedex/assets/sprites/44.gif', 'Lanza un olor tan intenso que nadie puede acercarse a menos de 1 km. Sin embargo, hay quien lo considera un buen olor.', 44),
(45, 'Vileplume', '/pokedex/assets/sprites/45.gif', 'Cuando florece, dispersa un polen nocivo y altamente alucinógeno que causa estornudos y llanto.', 45),
(46, 'Paras', '/pokedex/assets/sprites/46.gif', 'Crece alimentándose de la savia de los árboles. Se desplaza muy lentamente.', 46),
(47, 'Parasect', '/pokedex/assets/sprites/47.gif', 'El parásito se apodera del cuerpo y el alma de Parasect. La seta crece sobre él y lo controla.', 47),
(48, 'Venonat', '/pokedex/assets/sprites/48.gif', 'Sus grandes ojos son extremadamente sensibles a la luz. Por eso, vive en cuevas oscuras y húmedas.', 48),
(49, 'Venomoth', '/pokedex/assets/sprites/49.gif', 'Su cuerpo está cubierto de escamas en las que se encuentran toxinas que provocan parálisis.', 49),
(50, 'Diglett', '/pokedex/assets/sprites/50.gif', 'Vive en el subsuelo y es capaz de excavar un túnel de 100 metros en una noche de luna llena.', 50),
(51, 'Dugtrio', '/pokedex/assets/sprites/51.gif', 'Excava un túnel de 100 kilómetros de longitud en una sola noche de luna llena.', 51),
(52, 'Meowth', '/pokedex/assets/sprites/52.gif', 'Tiene un carácter extremadamente feroz. Sin embargo, una vez que se familiariza con alguien, se comporta cariñosamente.', 52),
(53, 'Persian', '/pokedex/assets/sprites/53.gif', 'Sus largas y delgadas extremidades le permiten caminar sin hacer ruido. Es un depredador nocturno.', 53),
(54, 'Psyduck', '/pokedex/assets/sprites/54.gif', 'Más que usar la capacidad cerebral que tiene en la cabeza, parece que utiliza su corazón para luchar.', 54),
(55, 'Golduck', '/pokedex/assets/sprites/55.gif', 'Es un nadador muy competente. Se ha dicho que podría cruzar el Canal de la Mancha nadando.', 55),
(56, 'Mankey', '/pokedex/assets/sprites/56.gif', 'Vive en bosques densos. Cuando se enfada, se desata y no se calma hasta que no ha destrozado todo.', 56),
(57, 'Primeape', '/pokedex/assets/sprites/57.gif', 'Con la fuerza de sus brazos, es capaz de doblar una viga de acero. Es muy difícil de controlar.', 57),
(58, 'Growlithe', '/pokedex/assets/sprites/58.gif', 'Es muy leal a su entrenador y lo defiende de cualquier ataque, por peligroso que sea.', 58),
(59, 'Arcanine', '/pokedex/assets/sprites/59.gif', 'Es capaz de correr a 100 km/h. Su melena arde en el mismo tono que el fuego que echa por la boca.', 59),
(60, 'Poliwag', '/pokedex/assets/sprites/60.gif', 'Se dice que el vórtice que lleva en el abdomen se originó en las inagotables fuentes de agua.', 60),
(61, 'Poliwhirl', '/pokedex/assets/sprites/61.gif', 'La espiral que lleva en el abdomen contiene un líquido. Dicen que puede regenerar extremidades amputadas.', 61),
(62, 'Poliwrath', '/pokedex/assets/sprites/62.gif', 'Su cuerpo es resistente a los golpes. Los puñetazos de Poliwrath pueden partir un bloque de cemento con facilidad.', 62),
(63, 'Abra', '/pokedex/assets/sprites/63.gif', 'Es muy tímido y suele esconderse en la hierba. Se le escapa si te descuidas.', 63),
(64, 'Kadabra', '/pokedex/assets/sprites/64.gif', 'Ha demostrado tener una capacidad intelectual muy alta. Puede prever el futuro por la posición de las estrellas.', 64),
(65, 'Alakazam', '/pokedex/assets/sprites/65.gif', 'Sus células cerebrales se han multiplicado tanto que ha desarrollado más poderes. Es un Pokémon muy inteligente.', 65),
(66, 'Machop', '/pokedex/assets/sprites/66.gif', 'Más que usar la capacidad cerebral que tiene en la cabeza, parece que utiliza su corazón para luchar.', 66),
(67, 'Machoke', '/pokedex/assets/sprites/67.gif', 'Es muy fuerte y es capaz de lanzar un golpe tan potente que es capaz de derribar a un elefante.', 67),
(68, 'Machamp', '/pokedex/assets/sprites/68.gif', 'Su fuerza es ilimitada. Puede lanzar cien golpes por segundo y alcanzar una velocidad de mach 2.', 68),
(69, 'Bellsprout', '/pokedex/assets/sprites/69.gif', 'Cuando detecta la presa, se balancea y lanza el tentáculo como un látigo para atraparla.', 69),
(70, 'Weepinbell', '/pokedex/assets/sprites/70.gif', 'Atrae a sus presas con una dulce fragancia que desprende de la babosa que tiene en la cabeza.', 70),
(71, 'Victreebel', '/pokedex/assets/sprites/71.gif', 'Devora a su presa sin piedad. Sus enormes fauces le permiten tragar cosas grandes de un solo bocado.', 71),
(72, 'Tentacool', '/pokedex/assets/sprites/72.gif', 'En aguas cálidas, nadan en grupos. Se dice que las mareas aumentan cuando aparecen.', 72),
(73, 'Tentacruel', '/pokedex/assets/sprites/73.gif', 'Su cuerpo está formado por más del 90% de agua. A veces, arrasa pueblos enteros en la costa.', 73),
(74, 'Geodude', '/pokedex/assets/sprites/74.gif', 'Cuando se le acaba la energía, se convierte en una roca y se queda dormido. Hasta el ruido de una demolición lo despierta.', 74),
(75, 'Graveler', '/pokedex/assets/sprites/75.gif', 'Le gusta rodar colina abajo para desplazarse. A veces, se cae por los acantilados sin querer.', 75),
(76, 'Golem', '/pokedex/assets/sprites/76.gif', 'Pesa más de 600 kg. Si empieza a rodar colina abajo, nada puede pararlo.', 76),
(77, 'Ponyta', '/pokedex/assets/sprites/77.gif', 'Galopa a toda velocidad. Siempre que hay corrientes de aire, se le puede ver corriendo por las llanuras a toda velocidad.', 77),
(78, 'Rapidash', '/pokedex/assets/sprites/78.gif', 'Posee una velocidad de vértigo. Siempre que corre, se envuelve en llamas.', 78),
(79, 'Slowpoke', '/pokedex/assets/sprites/79.gif', 'Su cuerpo está relleno de órganos muy lentos. Parece que hay algo que lo hace funcionar más lento de lo normal.', 79),
(80, 'Slowbro', '/pokedex/assets/sprites/80.gif', 'Si alguien le arranca la concha, se le despierta un poder oculto y se vuelve mucho más violento.', 80),
(81, 'Magnemite', '/pokedex/assets/sprites/81.gif', 'Está compuesto de magnetita. Algunas veces, se junta con otros Magnemite y forman un Magneton.', 81),
(82, 'Magneton', '/pokedex/assets/sprites/82.gif', 'Si uno de los imanes falla, se separa del grupo y se convierte en un Magnemite independiente.', 82),
(83, 'Farfetch’d', '/pokedex/assets/sprites/83.gif', 'Este Pokémon salvaje lleva un puerro en la ala todo el tiempo. Se lo come junto con las setas que encuentra.', 83),
(84, 'Doduo', '/pokedex/assets/sprites/84.gif', 'Corre muy rápido y no necesita alas para volar. Despliega sus dos cabezas para darle más velocidad.', 84),
(85, 'Dodrio', '/pokedex/assets/sprites/85.gif', 'No puede volar, pero salta muy alto. En una lucha, puede clavar las tres cabezas en su rival a la vez.', 85),
(86, 'Seel', '/pokedex/assets/sprites/86.gif', 'Se le encuentra con frecuencia en zonas con temperaturas bajo cero. En la orilla de los lagos se ve a menudo a Seel jugando en la nieve.', 86),
(87, 'Dewgong', '/pokedex/assets/sprites/87.gif', 'Es muy juguetón y suele hacer volteretas y piruetas. A veces las hace en la orilla del mar, saltando sobre las olas.', 87),
(88, 'Grimer', '/pokedex/assets/sprites/88.gif', 'Es un líquido viscoso con olor a desecho. Todo lo que toca se le pega.', 88),
(89, 'Muk', '/pokedex/assets/sprites/89.gif', 'Es muy elástico y puede estirarse para capturar a su presa. A veces se cae y se queda pegajoso.', 89),
(90, 'Shellder', '/pokedex/assets/sprites/90.gif', 'Se adhiere firmemente a las rocas y no se mueve de ahí. Se alimenta de algas que flotan en el agua.', 90),
(91, 'Cloyster', '/pokedex/assets/sprites/91.gif', 'El órgano interno que tiene en la concha es muy duro. Puede soportar incluso los ataques más fuertes.', 91),
(92, 'Gastly', '/pokedex/assets/sprites/92.gif', 'Es capaz de ocultarse en la oscuridad. Puede meterse en cualquier sitio sin que nadie lo note.', 92),
(93, 'Haunter', '/pokedex/assets/sprites/93.gif', 'Si sientes un frío repentino, es una señal de que un Haunter está cerca. Dicen que los fantasmas lo producen.', 93),
(94, 'Gengar', '/pokedex/assets/sprites/94.gif', 'Lanza maldiciones de terror. Puede entrar en la sombra de cualquiera y aparecer de la oscuridad.', 94),
(95, 'Onix', '/pokedex/assets/sprites/95.gif', 'Excava túneles subterráneos de 10 km de profundidad para encontrar minerales.', 95),
(96, 'Drowzee', '/pokedex/assets/sprites/96.gif', 'Duerme el 18 horas al día. Le encanta comer los sueños de la gente.', 96),
(97, 'Hypno', '/pokedex/assets/sprites/97.gif', 'Atrae a la gente con su extraño hipnotismo y les roba los sueños que tienen en la fase REM.', 97),
(98, 'Krabby', '/pokedex/assets/sprites/98.gif', 'Es de mar abierto, pero suele subir a ríos y arroyos. Se le puede ver cazando en la orilla.', 98),
(99, 'Kingler', '/pokedex/assets/sprites/99.gif', 'Es un buen nadador. También puede vivir en tierra, pero se mantiene alejado de la arena.', 99),
(100, 'Voltorb', '/pokedex/assets/sprites/100.gif', 'Es extremadamente sensible a las fuerzas magnéticas. Se dice que pueden ser causadas por su propio magnetismo.', 100),
(101, 'Electrode', '/pokedex/assets/sprites/101.gif', 'Es muy peligroso. Tiene un gran poder explosivo. Quienes lo ven caminar sobre su propia energía huyen aterrorizados.', 101),
(102, 'Exeggcute', '/pokedex/assets/sprites/102.gif', 'Suelen juntarse seis y dormir en grupo. El grupo completo se despierta si alguno de los seis se asusta.', 102),
(103, 'Exeggutor', '/pokedex/assets/sprites/103.gif', 'Los Exeggutor más altos tienen cabeza en su cola. La cabeza tarda cinco segundos en darse cuenta de que está siendo atacada.', 103),
(104, 'Cubone', '/pokedex/assets/sprites/104.gif', 'Carga un hueso que encontró de su madre muerta. Hay quienes afirman haber visto la figura de la madre en la luna mientras llora.', 104),
(105, 'Marowak', '/pokedex/assets/sprites/105.gif', 'Su espada es una maravilla de la naturaleza. Dicen que puede atravesar una piedra con una simple sacudida de su cola.', 105),
(106, 'Hitmonlee', '/pokedex/assets/sprites/106.gif', 'Extiende sus piernas para hacer una gama amplia de golpes que ningún otro Pokémon puede igualar.', 106),
(107, 'Hitmonchan', '/pokedex/assets/sprites/107.gif', 'Le gusta cerrar el ring con su punzón en la mano. A veces gana sin tener que pelear.', 107),
(108, 'Lickitung', '/pokedex/assets/sprites/108.gif', 'Se mueve lentamente, pero su lengua es increíblemente rápida. Puede lamer a 100 personas en menos de una hora.', 108),
(109, 'Koffing', '/pokedex/assets/sprites/109.gif', 'Se desplaza a la deriva por el aire. Si encuentra una presa, expulsa gas venenoso de su cuerpo.', 109),
(110, 'Weezing', '/pokedex/assets/sprites/110.gif', 'Le gusta más el aire limpio. Se alimenta de gases venenosos que encuentra por ahí.', 110),
(111, 'Rhyhorn', '/pokedex/assets/sprites/111.gif', 'En una lucha, puede partir un árbol de un solo cabezazo. Una embestida suya puede destruir un edificio.', 111),
(112, 'Rhydon', '/pokedex/assets/sprites/112.gif', 'Es increíblemente fuerte. Su cuerno tiene la dureza de diamante y puede perforar fácilmente cualquier cosa.', 112),
(113, 'Chansey', '/pokedex/assets/sprites/113.gif', 'Se le considera de buen agüero. Se dice que quien ve a uno podrá vivir una vida feliz y plena.', 113),
(114, 'Tangela', '/pokedex/assets/sprites/114.gif', 'Cuando está muy excitado, su cuerpo se extiende, lo que le permite a Tangela atrapar a sus presas con facilidad.', 114),
(115, 'Kangaskhan', '/pokedex/assets/sprites/115.gif', 'Se dice que la madre se pelea por su cría. Vive en el bosque.', 115),
(116, 'Horsea', '/pokedex/assets/sprites/116.gif', 'Puede nadar en el mar o en los ríos. A veces, nada en grupos de 100 o más.', 116),
(117, 'Seadra', '/pokedex/assets/sprites/117.gif', 'Caza usando el rabo como si fuera un látigo para atrapar a su presa. La engulle cuando está medio muerta.', 117),
(118, 'Goldeen', '/pokedex/assets/sprites/118.gif', 'Cuando nada río arriba para desovar, es fácil verlo saltando por las cataratas.', 118),
(119, 'Seaking', '/pokedex/assets/sprites/119.gif', 'Es muy agresivo y ataca con cuerno y cola. Durante la época de cría, su rojo cuerno crece enormemente.', 119),
(120, 'Staryu', '/pokedex/assets/sprites/120.gif', 'Los cristales que lleva en su cuerpo son muy valorados como gema. Dicen que se parecen a una estrella.', 120),
(121, 'Starmie', '/pokedex/assets/sprites/121.gif', 'Su cuerpo es de cristal. Se dice que se originó en un meteorito que cayó en las montañas hace tiempo.', 121),
(122, 'Mr. Mime', '/pokedex/assets/sprites/122.gif', 'Es muy hábil en la imitación. Es capaz de hacer parecer que la realidad es una ilusión y viceversa.', 122),
(123, 'Scyther', '/pokedex/assets/sprites/123.gif', 'Sus afiladas garras son poderosas armas. Pueden partir un árbol de un solo golpe.', 123),
(124, 'Jynx', '/pokedex/assets/sprites/124.gif', 'Baila de forma sexy para confundir a sus rivales y lanza un potente beso que congela al instante.', 124),
(125, 'Electabuzz', '/pokedex/assets/sprites/125.gif', 'Se encuentra con frecuencia en tormentas eléctricas. Le gusta mucho la electricidad.', 125),
(126, 'Magmar', '/pokedex/assets/sprites/126.gif', 'Las llamas ardientes que escupe por la boca son de 2.200 grados. Siempre está respirando fuego.', 126),
(127, 'Pinsir', '/pokedex/assets/sprites/127.gif', 'Es muy fuerte y se le teme. Con sus potentes mandíbulas, puede cortar un árbol de un solo mordisco.', 127),
(128, 'Tauros', '/pokedex/assets/sprites/128.gif', 'Este Pokémon se enfurece con la más mínima provocación y no se calma hasta que no ha destruido todo a su paso.', 128),
(129, 'Magikarp', '/pokedex/assets/sprites/129.gif', 'Puede sobrevivir en cualquier medio acuático. Incluso puede vivir en aguas contaminadas.', 129),
(130, 'Gyarados', '/pokedex/assets/sprites/130.gif', 'Dicen que cuando enfurece, causa tormentas. En algunas regiones, se le conoce como el destructor.', 130),
(131, 'Lapras', '/pokedex/assets/sprites/131.gif', 'Es muy inteligente y es capaz de entender el lenguaje humano. Tiene un alto sentido de la justicia.', 131),
(132, 'Ditto', '/pokedex/assets/sprites/132.gif', 'Puede cambiar de forma para parecerse a cualquier Pokémon o persona. Dicen que siempre es una copia exacta.', 132),
(133, 'Eevee', '/pokedex/assets/sprites/133.gif', 'Puede evolucionar en varios tipos diferentes dependiendo de la piedra que lleve.', 133),
(134, 'Vaporeon', '/pokedex/assets/sprites/134.gif', 'Su piel se convierte en una fina capa que le permite nadar a gran velocidad.', 134),
(135, 'Jolteon', '/pokedex/assets/sprites/135.gif', 'Sus finos pelos generan electricidad estática. Pueden provocar descargas eléctricas al tocarlo.', 135),
(136, 'Flareon', '/pokedex/assets/sprites/136.gif', 'La temperatura de su cuerpo aumenta cuando se siente emocionado. En ese momento, libera una cantidad de calor impresionante.', 136),
(137, 'Porygon', '/pokedex/assets/sprites/137.gif', 'Se formó por la programación de una computadora. Es capaz de moverse y pensar de forma independiente.', 137),
(138, 'Omanyte', '/pokedex/assets/sprites/138.gif', 'Vivía en los mares hace 100 millones de años. Se encuentra con frecuencia entre fósiles de conchas.', 138),
(139, 'Omastar', '/pokedex/assets/sprites/139.gif', 'Una vez que tiene enemigos a la vista, dispara tentáculos pegajosos para atraparlos y luego los devora.', 139),
(140, 'Kabuto', '/pokedex/assets/sprites/140.gif', 'Vivió hace 300 millones de años. Se considera un fósil, pero sigue siendo capaz de vivir en el agua.', 140),
(141, 'Kabutops', '/pokedex/assets/sprites/141.gif', 'Cuando entra en contacto con agua, Kabutops puede respirar y moverse con facilidad.', 141),
(142, 'Aerodactyl', '/pokedex/assets/sprites/142.gif', 'Este Pokémon es un antiguo habitante de los cielos. Se cree que era capaz de volar.', 142),
(143, 'Snorlax', '/pokedex/assets/sprites/143.gif', 'Siempre está durmiendo y comiendo. Nunca deja de buscar comida ni de dormir.', 143),
(144, 'Articuno', '/pokedex/assets/sprites/144.gif', 'Es un legendario pájaro Pokémon que puede congelar el aire húmedo en su entorno para crear una tormenta de nieve.', 144),
(145, 'Zapdos', '/pokedex/assets/sprites/145.gif', 'Es un legendario pájaro Pokémon que crea rayos al agitar sus alas. Se dice que causa tormentas eléctricas.', 145),
(146, 'Moltres', '/pokedex/assets/sprites/146.gif', 'Es un legendario pájaro Pokémon que puede controlar el fuego. Vuela por el cielo arrojando llamas.', 146),
(147, 'Dratini', '/pokedex/assets/sprites/147.gif', 'Sus largas aletas le permiten nadar a una velocidad de 8 nudos. Es un excelente nadador.', 147),
(148, 'Dragonair', '/pokedex/assets/sprites/148.gif', 'Es capaz de volar a una altitud de 6.600 pies. A veces se le ve volando a lo largo de las laderas de las montañas.', 148),
(149, 'Dragonite', '/pokedex/assets/sprites/149.gif', 'Es una criatura muy amable. Aunque su fuerza y ​​ferocidad lo convierten en un poderoso oponente en la batalla.', 149),
(150, 'Mewtwo', '/pokedex/assets/sprites/150.gif', 'Un Pokémon artificial creado mediante ingeniería genética. Se dice que fue creado a partir del ADN de Mew.', 150),
(151, 'Mew', '/pokedex/assets/sprites/151.gif', 'Es capaz de aprender y usar cualquier movimiento de Pokémon. Su ADN es muy parecido al de Mewtwo.', 151);

-- Indices de la tabla `pokemon`
ALTER TABLE `pokemon`
  ADD PRIMARY KEY (`Id`);

-- AUTO_INCREMENT de la tabla `pokemon`
ALTER TABLE `pokemon`
  MODIFY `Id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=153;
COMMIT;